### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by C4Wiz** [dmacias72/IPMI-unRAID#1]
would it be possible to zone headers 1,2,3,4 further?

IE: FAN1, FAN2, FAN3= HDD Temp FAN4= Chassis

**Comment by dmacias72** [comment]
Only ASRock boards allow for individual fan control. Supermicro IPMI only has commands for FANA and FAN1234 zones. So I use FANA for my hard drives based on hard drive temp. I use FAN1234 for my system based on CPU temp.

**Comment by C4Wiz** [comment]
oh, gotcha. thats a bummer... thank you for the explanation. i use fanA for CPU cooler, FAN1234 for Chassis cooling based on HDD temps
